# Generated by Django 5.0.3 on 2024-03-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
