# Generated by Django 5.0.3 on 2024-04-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
